### PR TITLE
Allow converting image URLs to favicons

### PR DESCRIPTION
**Pull request by max-arias**
This will check if the provided `-f` is a local file, if not it will download from the web. 

Once the image is downloaded, it will be written to the local file system and then converted to a favicon.

@Youngestdev  let me know what you think!

### CODE REVIEW

**Comment by Youngestdev** [comment]
Hi, I'll be reviewing this :tada:

**Comment by Youngestdev** [comment]
@max-arias  Yay !. It works, here's a couple of things I'm thinking. Porting the favicon generator to an electron app. Do you have any idea on how electronJS works ?

**Comment by max-arias** [comment]
Hey @Youngestdev write up a few more issues and throw it up for Hacktoberfest, maybe someone can help out. :) gl!

**Comment by Youngestdev** [comment]
Aye! . Thanks for helping and reaching out !.

**Pull request merged**
